image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - git clone https://gitlab.com/gbraad/Fedora-Dockerfiles.git dockerfiles --depth 1
  
build_ansible:
  script:
    - docker build -t registry.gitlab.com/gbraad/fedora:ansible ./dockerfiles/ansible 
    - docker push registry.gitlab.com/gbraad/fedora:ansible
  only:
    - master
